In [1]:
import pandas as pd
import json

In [33]:
with open('security_data.json') as file:
    json_data = json.load(file)

events = pd.DataFrame(json_data['events'])
entities = pd.DataFrame(json_data['entities'])
relationships = pd.DataFrame(json_data['relationships'])

attack_scenarios = pd.DataFrame(json_data['ground_truth']['attack_scenarios'])

In [35]:
events

,id,type,timestamp,severity,description,alert_style,alert_message
0,224a7b52-a126-44bc-90d4-301ab4de4664,Authentication,2025-05-30T21:55:58.061710,6,Service account used interactively,raw_telemetry,Windows Event ID 4624: Service account used in...
1,c5d5885f-5c1b-41c2-a3c4-2fa7fe4074a0,Defense Evasion,2025-05-31T05:15:42.002908,8,Logs cleared or deleted,behavioral,POTENTIAL DEFENSE EVASION: Logs cleared or del...
2,c7e0c496-a7b1-433b-8cc6-a5e4e7ad8cfa,Authentication,2025-05-31T09:40:32.084221,8,Lateral movement to critical system,raw_telemetry,RAW_TELEMETRY ALERT: Lateral movement to criti...
3,30d15fa0-0a9b-4888-85a5-f5e19950b5fa,Privilege Operation,2025-05-31T10:17:30.872790,7,Scheduled task created for persistence,raw_telemetry,Process chrome.exe started with elevated privi...
4,312b0a4c-e101-4533-9105-dd57877e7406,Data Access,2025-05-31T10:40:12.918836,9,Access to credentials store,rules_based,RULES_BASED ALERT: Access to credentials store...
...,...,...,...,...,...,...,...
1007,23bfc397-f876-4317-95f0-d54401399faa,Authentication,2025-05-25T12:44:29.058975,1,Service account used interactively,raw_telemetry,Windows Event ID 4624: Service account used in...
1008,7189d907-9157-45ed-97ae-88045deba4ed,Authentication,2025-05-26T04:47:52.549541,1,Service account used interactively,raw_telemetry,RAW_TELEMETRY ALERT: Service account used inte...
1009,7ed85397-8dcb-4108-bffd-5032799d4c3b,Authentication,2025-05-27T23:22:05.782057,3,Login outside business hours,behavioral,USER BEHAVIOR CHANGE: Login outside business h...
1010,4c1a0297-044f-4e6b-9e8b-262d68710be6,Exfiltration,2025-05-28T05:45:19.167575,1,Data compressed prior to exfiltration,raw_telemetry,RAW_TELEMETRY ALERT: Data compressed prior to ...
1011,01faa212-deb6-4954-853f-c78d31130a0d,Authentication,2025-05-27T17:54:30.609891,3,Authentication with expired credentials,raw_telemetry,RAW_TELEMETRY ALERT: Authentication with expir...

In [36]:
entities

,id,type,name,properties
0,8f631dee-f673-4fe6-8c3c-074e2901081e,Host,WS-223,"{'hostname': 'WS-223', 'ip_address': '192.168...."
1,ef907219-e4f7-4cfc-81e9-9dabb7917b10,Host,DC-252,"{'hostname': 'DC-252', 'ip_address': '192.168...."
2,9cc327ae-7f24-46e8-a5d6-5c6fe604fd2d,Host,SRV-159,"{'hostname': 'SRV-159', 'ip_address': '192.168..."
3,2e142e0f-35a1-4561-8c5a-bcf11340a87e,User,Jane Smith,"{'username': 'jsmith', 'role': 'Admin', 'depar..."
4,38e9afa0-3302-4a3c-bfe7-a45376079197,User,Jane Johnson,"{'username': 'jjohnson', 'role': 'Analyst', 'd..."
...,...,...,...,...
1381,02c202e4-7758-4861-9cc9-568734c63be9,Host,APP-213,"{'hostname': 'APP-213', 'ip_address': '192.168..."
1382,ef0ba623-5416-49b2-a734-1bfb734320c8,Host,DC-141,"{'hostname': 'DC-141', 'ip_address': '192.168...."
1383,7993e9ac-7e3e-429e-b191-354442a09d18,NetworkConnection,192.168.40.23:8080 -> 66.140.50.219,"{'source_ip': '192.168.40.23', 'dest_ip': '66...."
1384,75044943-a681-4dc8-bae5-93a6b4e381f4,NetworkConnection,192.168.130.124:53 -> 192.168.173.205,"{'source_ip': '192.168.130.124', 'dest_ip': '1..."
1385,46ec1e62-f91b-491e-ad01-f3f6c1811838,User,Emma Brown,"{'username': 'ebrown', 'role': 'Manager', 'dep..."

In [37]:
relationships

,source,target,weight,type
0,224a7b52-a126-44bc-90d4-301ab4de4664,2e142e0f-35a1-4561-8c5a-bcf11340a87e,1.000000,related_to
1,224a7b52-a126-44bc-90d4-301ab4de4664,ef907219-e4f7-4cfc-81e9-9dabb7917b10,1.000000,related_to
2,224a7b52-a126-44bc-90d4-301ab4de4664,8f631dee-f673-4fe6-8c3c-074e2901081e,1.000000,related_to
3,224a7b52-a126-44bc-90d4-301ab4de4664,0ff189fc-a3a4-4fcf-b05f-180af33a872b,1.000000,related_to
4,224a7b52-a126-44bc-90d4-301ab4de4664,9cc327ae-7f24-46e8-a5d6-5c6fe604fd2d,1.000000,related_to
...,...,...,...,...
3855,7ed85397-8dcb-4108-bffd-5032799d4c3b,75044943-a681-4dc8-bae5-93a6b4e381f4,0.721016,related_to
3856,7ed85397-8dcb-4108-bffd-5032799d4c3b,46ec1e62-f91b-491e-ad01-f3f6c1811838,0.967944,related_to
3857,4c1a0297-044f-4e6b-9e8b-262d68710be6,02c202e4-7758-4861-9cc9-568734c63be9,0.338000,related_to
3858,01faa212-deb6-4954-853f-c78d31130a0d,99682a04-80ed-4f37-aa82-822f545f66f5,0.395000,related_to
3859,01faa212-deb6-4954-853f-c78d31130a0d,02c202e4-7758-4861-9cc9-568734c63be9,0.395000,related_to

In [34]:
'''
Sanity Check
====================================================================================
The event_ids that appear in the ground_truth.attack_scenarios array are precisely
those that are listed ground_truth.true_positive_events.
'''

e = [event for i in range(len(attack_scenarios)) for event in attack_scenarios['event_ids'][i]]
print(set(e) == set(json_data['ground_truth']['true_positive_events'])) # should print true

'''
Likewise, the entity_ids that appear in the ground_truth.attack_scenarios array are precisely
those that are listed ground_truth.true_positive_entities.
'''

e = [entity for i in range(len(attack_scenarios)) for entity in attack_scenarios['entity_ids'][i]]
print(set(e) == set(json_data['ground_truth']['true_positive_entities'])) # should print true

True
True